analytics: {}
color:
  brandColors:
    - '#000000'
    - '#a0a0a0'
    - '#324459'
    - '#727272'
    - '#ffffff'
  brandStrength: 0.32348
  lightness: 0.1888
  rhythmicContrast: 0.504188
  saturation: 0.934465
cta: {}
layout_spectrum: 0.49761
name: Ewan Richardson Photographs
opengraph: {}
purpose: []
typography_spectrum: 0.31588
