name: Ewan Richardson Photographs
favicon: null
layout_spectrum: 0.49761
typography_spectrum: 0.31588
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#a0a0a0'
    - '#324459'
    - '#727272'
    - '#ffffff'
  brandStrength: 1
  lightness: 0.18880013190209866
  saturation: 0.9344651096034795
  rhythmicContrast: 0.5041885040700436
purpose: []
