name: Ewan Richardson Photographs
favicon: null
layout_spectrum: 0.77413
typography_spectrum: 0.31588
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#a0a0a0'
    - '#324459'
    - '#727272'
    - '#ffffff'
  brandStrength: 0.0625
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0
purpose: []
